apiVersion: v1
kind: ResourceQuota
metadata:
  name: nginx-cpu-memory
  namespace: nginx-resource
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi