apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }} 
data:
  config.json: |
    {
      "app_mode": "prod",
      "db_type": "mysql",
      "db_url": "mysql-service",
      "db_user": "root",
      "db_psw": "qa12345",
      "db_port": 3306,
      "db_name": "demo"
    }
  default.conf: |
    server {
    listen       8080;
    server_name  localhost;

    location / {
        proxy_pass http://localhost:8000;
    }
    } 
