apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: flask-example

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- flask-config.yaml

configMapGenerator:
- files:
  - default.conf
  name: nginx-config