apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins-server.fullname" . }}
  labels:
    {{- include "jenkins-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ index .Values "jenkins-port" }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jenkins-server.selectorLabels" . | nindent 4 }}
