apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-volume
spec:
  containers:
  - image: nginx
    name: nginx-pod-volume
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: Directory