apiVersion: v1
kind: Service
metadata:
  name: playwright-service
  labels:
    app: playwright-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: port

  selector:
    app: playwright-server