apiVersion: v1
kind: Service
metadata:
  name: playwright-service
  labels:
    app: playwright-service
spec:
  ports:
    - name: playwright
      port: 3000
      targetPort: 3000
      protocol: TCP

  selector:
    app: playwright-server