apiVersion: apps/v1
kind: Deployment
metadata:
  name: playwright-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playwright-server
  template:
    metadata:
      labels:
        app: playwright-server
    spec:
      containers:
        - name: playwright
          image: mcr.microsoft.com/playwright:v1.48.0-jammy
          command: ["bin/bash","-c","npx -y playwright@1.48.0 run-server --port 3000"]
          ports:
            - containerPort: 3000