apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-example.fullname" . }}
spec:
  selector:  {{- include "flask-example.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
