apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: mysql

resources:
- mysql-config.yaml
- mysql-pv-pvc.yaml
- mysql-deploy.yaml
- mysql-service.yaml
- mysql-secret.yaml

