- name: Gather system information
  ansible.builtin.setup:
    filter: "ansible_*"

- name: Print the hostname
  debug:
    msg: "The hostname of the system is {{ ansible_hostname }}"

- name: Print the operating system details
  debug:
    msg: "The OS is {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_distribution_release }})"

- name: Print the total memory
  debug:
    msg: "The total memory is {{ ansible_memtotal_mb }} MB"

- name: Print the CPU architecture
  debug:
    msg: "The CPU architecture is {{ ansible_architecture }}"

- name: Print memory stat
  shell: |
    free -h
