apiVersion: v1
kind: Service
metadata:
  name: {{ include "playwright-service.fullname" . }}
  labels:
    {{- include "playwright-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: 
  {{- range $key, $value := .Values.ports }}
    - name: {{ $key }}
      port: {{ $value }}
      targetPort: {{ $value }}
  {{- end }}

  selector:
    {{- include "playwright-service.selectorLabels" . | nindent 4 }}
