- name: start zookeeper cluster
  shell: /opt/kafka_2.10-0.10.2.1/bin/zookeeper-server-start.sh -daemon /opt/kafka_2.10-0.10.2.1/config/zookeeper.properties

- name: start kafka cluster
  shell: bash  /opt/kafka_2.10-0.10.2.1/bin/kafka-server-start.sh -daemon /opt/kafka_2.10-0.10.2.1/config/server.properties
