apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-network-policy
  namespace: default
spec:
  policyTypes:
  - Ingress
  - Egress
  egress:
    - {}
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 80
  podSelector: {}