# Default values for CI_CD_helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

flask-example:
  fullnameOverride: flask-example
  image:
    repository: ericxiwang/flask
    pullPolicy: IfNotPresent
    tag: "042424"
  service:
    type: ClusterIP
    port: 8080
  mode: "dev" # "dev" or "prod"
jenkins-server:
  fullnameOverride: jenkins-server
  image: docker.io/ericxiwang/jenkins
  tag: "042424"
  jenkins-port: 8080
selenium-service:
  fullnameOverride: selenium-service
  image: 
    repository: selenium/standalone-chrome
    pullPolicy: IfNotPresent
    tag: latest
  ports:
    port-1: 4444
    port-2: 4443
    port-3: 4442
    port-4: 7900
