apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:

  name: deployment-clusterrole
rules:
- apiGroups: [""]

  resources: ["Deployment","StatefulSet","DaemonSet"]
  verbs: ["create"]

---
  apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: cicd-token
  namespace: app-team1


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cicd-role-binding
subjects:

- kind: ServiceAccount
  name: cicd-token
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: deployment-clusterrole
  apiGroup: rbac.authorization.k8s.io
