apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS demo;
    USE demo;
    CREATE TABLE IF NOT EXISTS user_info (id INTEGER AUTO_INCREMENT PRIMARY KEY,user_name TEXT,email TEXT,user_password TEXT,group_id INTEGER);
    CREATE TABLE IF NOT EXISTS image_info (id INTEGER AUTO_INCREMENT PRIMARY KEY,img_uuid TEXT,img_description TEXT,img_album TEXT);
    CREATE TABLE IF NOT EXISTS image_album (id INTEGER AUTO_INCREMENT PRIMARY KEY,album_name TEXT,album_description TEXT);
    INSERT INTO user_info (id, user_name, email, user_password, group_id) VALUES (1,'test','dev@admin.com',1234,1);
    INSERT INTO image_info VALUES (4,'bfb3bc1a-277a-11ea-9f3a-2e9a2b44aff7.jpg','Pairs','France');
    INSERT INTO image_info VALUES (5,'bfb3bc1b-277a-11ea-9f3a-2e9a2b44aff7.jpg','la','Spain');
    INSERT INTO image_info VALUES (6,'bfb3bc1c-277a-11ea-9f3a-2e9a2b44aff7.jpg','vancouver','Canada');
    INSERT INTO image_info VALUES (8,'825ece82-2936-11ea-bcc1-2e9a2b44aff7.jpg',NULL,'Israel');
    INSERT INTO image_info VALUES (11,'4a05e81a-293e-11ea-bcc1-2e9a2b44aff7.jpg',NULL,'Spain');
    INSERT INTO image_info VALUES (12,'224a15b2-2943-11ea-bcc1-2e9a2b44aff7.jpg',NULL,'Spain');
    INSERT INTO image_info VALUES (13,'224a15b3-2943-11ea-bcc1-2e9a2b44aff7.jpg',NULL,'Spain');
    INSERT INTO image_info VALUES (14,'224a15b4-2943-11ea-bcc1-2e9a2b44aff7.jpg',NULL,'Spain');
    INSERT INTO image_album VALUES (1,'Spain','la');
    INSERT INTO image_album VALUES (2,'Canada','vancouver');
    INSERT INTO image_album VALUES (3,'Israel','Tel-Aviv');
    INSERT INTO image_album VALUES (4,'France','Pairs');

  my.cnf: |
    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    secure-file-priv= NULL
    #lower_case_table_names = 1
    #skip_ssl
    # Custom config should go here
    !includedir /etc/mysql/conf.d/
