apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins-server
      #type: NodePort
  ports:
    - port: 8080
      targetPort: http
      name: http
        #nodePort: 32000