apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-1
data:
  index.html: |
    <html>
    <h2> This is Deployment-1 </h2>
    </html>
  default.conf: |
      server {
          listen       80;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html; #Change this line
            index  index.html index.htm;
        }
      }