apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-configmap
    #namespace: nginx-main
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          #resources:
          #limits:
          #  memory: "1000Mi"
          #  cpu: "800m"
          #requests:
          #  memory: "600Mi"
          #  cpu: "400m"
        volumeMounts:
          - name: nginx-config
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config-1
            items:
              - key: index.html
                path: index.html
              - key: default.conf
                path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-configmap
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
  externalIPs:
    - 10.0.0.81