apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-1
data:
#config file for gunicorn
  default.conf: |
      server 
      {
      listen 80;
      server_name demo.com;
      access_log  /var/log/nginx/example.log;

      location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }